# ###########################################
# ######## _________________________ ########
# ########|                         |########
# ########|      PlayerSupport      |########
# ########|           by            |########
# ########|         CodeHat         |########
# ########|  Licensed under GPLv3.  |########
# ########|_________________________|########
# ###########################################
# ###########################################
# ###########################################
# ###########################################
# CONFIG EXPLANATION:
# --------------------------------------------------------
# Sets the plugin language (de = german; en = english).
# language: en
# --------------------------------------------------------
# Should the plugin check for updates.
# updatecheck: true
# --------------------------------------------------------
# Metrics for mcstats.org.
# metrics: true
# --------------------------------------------------------
# DO NOT TOUCH THESE TWO LISTS!!!
# supporters: []
# deniedPlayers: []
# --------------------------------------------------------
# PLUGIN SETTINGS:
language: en
updatecheck: true
metrics: true
supporters: []
deniedPlayers: []