name: PlayerSupport
main: de.codehat.playersupport.PlayerSupport
author: CodeHat
website: https://codehat.de/
description: Let players request help from supporters.
version: 0.1

commands:
  support:
    description: Requests help or shows helprequests.
    usage: /<command>
    aliases: [sup]
    
permissions:
  playersupport.*:
    description: Access to all features.
    children:
      playersupport.support: true
      playersupport.info: true
      playersupport.help: true
      playersupport.reload: true
      playersupport.list: true
      playersupport.addsup: true
      playersupport.removesup: true
      playersupport.denyplayer: true
      playersupport.allowplayer: true
  playersupport.support:
    description: Allows you to request help.
  playersupport.info:
    description: Allows you to see the plugin info.
  playersupport.help:
    description: Allows you to see the help page.
  playersupport.reload:
    description: Allows you to reload the config file.
  playersupport.list:
    description: Allows you to see the helprequests.
  playersupport.addsup:
    description: Allows you to add supporters.
  playersupport.removesup:
    description: Allows you to remove supporters.
  playersupport.denyplayer:
    description: Allow you to deny player to use /sup.
  playersupport.allowplayer:
    description: Allow you to allow player to use /sup.